# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-02-27 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspark', '0005_auto_20200227_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='/home/projjal/Projects/Foodspark/foodspark/static/img', upload_to=b''),
        ),
    ]
